canine:
  base_filename: ./canine.png
  center:
    circle:
      horizontal:
      - '#626262'
      - '#424242'
      vertical:
      - '#626262'
      - '#424242'
    horizontal:
    - '#533953'
    - '#965696'
    - '#d353d3'
    line:
      vertical:
      - '#533953'
      - '#5c285c'
    triangle:
      vertical:
      - - '#858585'
      - - '#8c8c8c'
        - '#424242'
    vertical:
    - '#965696'
    - '#533953'
    - '#5c285c'
    - '#991999'
  craws:
  - '#ffff00'
  extra_outline: '#1a1a1a'
  left_part_1:
    circle:
      horizontal:
      - '#5d3939'
      - '#626262'
      vertical:
      - '#5d3939'
      - '#626262'
    horizontal:
    - '#bc7c7c'
    - '#ec6c6c'
    - '#5d3939'
    - '#ec6c6c'
    vertical:
    - '#bc7c7c'
    - '#c64646'
  left_part_2:
    circle:
      horizontal:
      - '#385b38'
      - '#626262'
      vertical:
      - '#385b38'
      - '#626262'
    horizontal:
    - '#73b373'
    - '#66e666'
    - '#385b38'
    - '#66e666'
    vertical:
    - '#73b373'
    - '#40c040'
  outline: '#000000'
  outlines:
  - '#000000'
  - '#1a1a1a'
  parts:
  - center
  - left_part_1
  - left_part_2
  - right_part_1
  - right_part_2
  - whole
  right_part_1:
    circle:
      horizontal:
      - '#365a5a'
      - '#626262'
      vertical:
      - '#365a5a'
      - '#626262'
    horizontal:
    - '#69a9a9'
    - '#5fdfdf'
    - '#365a5a'
    - '#5fdfdf'
    vertical:
    - '#69a9a9'
    - '#39b9b9'
  right_part_2:
    circle:
      horizontal:
      - '#626262'
      vertical:
      - '#626262'
    horizontal:
    - '#5f5fa0'
    - '#5959d9'
    vertical:
    - '#5f5fa0'
    - '#3333b3'
categories:
- pride
- sexual
- gender
- relationship
- romantic
- sub_culture
feline:
  base_filename: ./feline.png
  center:
    circle:
      horizontal:
      - '#939393'
      - '#4d4d4d'
      vertical:
      - '#939393'
      - '#4d4d4d'
    horizontal:
    - '#894989'
    - '#b939b9'
    line:
      vertical:
      - '#763676'
    triangle:
      vertical:
      - - '#4d4d4d'
        - '#737373'
      - - '#595959'
    vertical:
    - '#894989'
    - '#ac2cac'
    - '#763676'
  extra_outline: '#1a1a1a'
  left_part_1:
    circle:
      horizontal:
      - '#939393'
      vertical:
      - '#939393'
    horizontal:
    - '#894949'
    - '#b93939'
    vertical:
    - '#894949'
    - '#ac2c2c'
  left_part_2:
    circle:
      horizontal:
      - '#939393'
      vertical:
      - '#939393'
    horizontal:
    - '#498949'
    - '#39b939'
    - '#498949'
    - '#39b939'
    vertical:
    - '#498949'
    - '#2cac2c'
  outline: '#000000'
  outlines:
  - '#000000'
  - '#1a1a1a'
  parts:
  - center
  - left_part_1
  - left_part_2
  - right_part_1
  - right_part_2
  - whole
  right_part_1:
    circle:
      horizontal:
      - '#939393'
      vertical:
      - '#939393'
    horizontal:
    - '#498989'
    - '#39b9b9'
    vertical:
    - '#498989'
    - '#2cacac'
  right_part_2:
    circle:
      horizontal:
      - '#939393'
      vertical:
      - '#939393'
    horizontal:
    - '#494989'
    - '#3939b9'
    - '#494989'
    - '#3939b9'
    vertical:
    - '#494989'
    - '#2c2cac'
forms:
- canine
- feline
transparent_colors:
- '#bfa88f'
- '#ffff00'
