transparent_color: '#bfa88f'
paw_colors:
  outline: '#000000'
  extra_outline: '#1a1a1a'
  left_part_1:
    horizontal:
      - '#bc7c7c'
      - '#ec6c6c'
    vertical:
      - '#bc7c7c'
      - '#c64646'
  left_part_2:
    horizontal:
      - '#73b373'
      - '#66e666'
    vertical:
      - '#73b373'
      - '#40c040'
  right_part_1:
    horizontal:
      - '#69a9a9'
      - '#5fdfdf'
    vertical:
      - '#69a9a9'
      - '#39b9b9'
  right_part_2:
    horizontal:
      - '#5f5fa0'
      - '#5959d9'
    vertical:
      - '#5f5fa0'
      - '#3333b3'
  center:
    horizontal:
      - '#533953'
      - '#965696'
      - '#d353d3'
    vertical:
      - '#965696'
      - '#533953'
      - '#5c285c'
      - '#991999'
    line:
      vertical:
        - '#533953'
        - '#5c285c'
    triangle:
      - '#828282'
      - '#7b7b7b'
  craws:
    - '#ffff00'



